version: "3.7"
services:

  backend:
    build: ./app
    command: ["/app/tools/run.sh"]
    volumes:
      - static_volume:/app/staticfiles
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
    env_file:
      - .env
    networks:
      - network-backend
      - network-frontend

  frontend:
    build: ./frontend
    volumes:
      - www:/app/dist

  nginx:
    build: ./nginx
    volumes:
      - /home/ubuntu/logs:/var/logs
      - /home/ubuntu/certs:/etc/nginx/certs
      - www:/var/www/html:ro
      - static_volume:/static
      - /home/ubuntu/doccano/nginx/nginx.conf:/etc/nginx/nginx.conf
    env_file:
      - .env
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    depends_on:
      - backend
    networks:
      - network-frontend

volumes:
  static_volume:
  www:

networks:
  network-backend:
  network-frontend:
